
services:
  db: 
    image: monarca-v1
    # restart: always
    expose:
      - "5432"
    ports:
      - "25000:5432"
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: Monarca
      POSTGRES_USER: postgres
      #POSTGRES_HOST_AUTH_METHOD: trust
    container_name: monarca_database
    volumes:
      - ./DB/postgres:/var/lib/postgresql
